apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/network-policies/deny-all-ingress.yml
- resources/network-policies/allow-ingress-nginx.yml
- resources/network-policies/controller-cjoc-ingress.yml
- resources/network-policies/agent-controller-ingress.yml
- chart.yaml
transformers:
  - transformers/namespace-labels.yaml
patches:
  - path: patches/jenkins-sa-patch.yaml
    target:
      kind: ServiceAccount
      name: jenkins
